// Generated by purs bundle 0.13.8
var PS = {};
(function(exports) {
  "use strict";

  exports.isNull = function (value) {
    return value === null;
  };

  exports.isUndefined = function (value) {
    return value === undefined;
  };
})(PS["Foreign"] = PS["Foreign"] || {});
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Foreign"] = $PS["Foreign"] || {};
  var exports = $PS["Foreign"];
  var $foreign = $PS["Foreign"];
  exports["isNull"] = $foreign.isNull;
  exports["isUndefined"] = $foreign.isUndefined;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Foreign = $PS["Foreign"];                
  var when = function (predicate) {
      return function (fn) {
          return function (value) {
              var $0 = predicate(value) === true;
              if ($0) {
                  return fn(value);
              };
              return value;
          };
      };
  };
  var defaultWhen = function (predicate) {
      return function (defValue) {
          return function (value) {
              var $1 = predicate(value) === true;
              if ($1) {
                  return value;
              };
              return defValue;
          };
      };
  };
  var defaultWhenEmpty = function (defValue) {
      return function (value) {
          return defaultWhen(function (x) {
              return !(Foreign.isUndefined(x) || Foreign.isNull(x));
          })(defValue)(value);
      };
  };
  var valueWhenEmpty = function (defValue) {
      return function (value) {
          return defaultWhen(function (x) {
              return Foreign.isUndefined(x) || Foreign.isNull(x);
          })(defValue)(value);
      };
  };
  var showIfValueExist = valueWhenEmpty;
  exports["when"] = when;
  exports["defaultWhen"] = defaultWhen;
  exports["valueWhenEmpty"] = valueWhenEmpty;
  exports["defaultWhenEmpty"] = defaultWhenEmpty;
  exports["showIfValueExist"] = showIfValueExist;
})(PS);
module.exports = PS["Main"];
